# Generated by Django 4.1.7 on 2023-03-06 16:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dellApp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="User_Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Profile",
                    models.FileField(default="default_icon.png", upload_to="profiles/"),
                ),
                ("FullName", models.CharField(blank=True, max_length=25)),
                (
                    "Gender",
                    models.CharField(
                        blank=True,
                        choices=[("m", "male"), ("f", "female")],
                        default="",
                        max_length=5,
                    ),
                ),
                ("BirthDate", models.DateField(default=datetime.date(2023, 3, 6))),
                ("Mobile", models.IntegerField(blank=True, max_length=10)),
                ("Address", models.CharField(blank=True, max_length=100)),
                (
                    "Master",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="dellApp.master"
                    ),
                ),
            ],
            options={"db_table": "User_Profile",},
        ),
    ]
