# Generated by Django 4.1.7 on 2023-03-13 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dellApp", "0003_alter_user_profile_mobile"),
    ]

    operations = [
        migrations.RemoveField(model_name="user_profile", name="FullName",),
        migrations.AddField(
            model_name="user_profile",
            name="Full_Name",
            field=models.CharField(default="", max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user_profile",
            name="Address",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="user_profile",
            name="BirthDate",
            field=models.DateField(default="2022-08-25"),
        ),
        migrations.AlterField(
            model_name="user_profile",
            name="Gender",
            field=models.CharField(
                choices=[("m", "male"), ("f", "female")], default="", max_length=5
            ),
        ),
        migrations.AlterField(
            model_name="user_profile",
            name="Mobile",
            field=models.CharField(max_length=10),
        ),
    ]
