# Generated by Django 4.1.7 on 2023-03-13 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "dellApp",
            "0004_remove_user_profile_fullname_user_profile_full_name_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="user_profile", old_name="Profile", new_name="Image",
        ),
    ]
